### ISSUE TITLE
Sample Docker Compose File produces yaml parser errors

### ISSUE THREAD

**Issue by StewAlexanderACC** [opendistro/for-elasticsearch-docs#140]
Opened ticket:
https://github.com/opendistro-for-elasticsearch/community/issues/137

Not sure where the issue needs to be put, but I am seeing yaml parser errors when I attempt to use the Sample Docker Composer File located at: https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/#sample-docker-compose-file

The errors I see (which I posted in the community ticket) are:
```
support@guacamole-docker:~/open-distro-elasticsearch$ docker-compose up
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 1, column 1
expected <block end>, but found '<scalar>'
  in "./docker-compose.yml", line 1, column 14
```

Info about my environment:
```
support@guacamole-docker:~/open-distro-elasticsearch$ docker --version
Docker version 19.03.5, build 633a0ea838
```

```
support@guacamole-docker:~/open-distro-elasticsearch$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by StewAlexanderACC** [comment]
Output of the docker-compose.yml file (just a copy and paste of the sample at 
https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/#sample-docker-compose-file)
```
version: '3'
services:
  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:1.2.0
    container_name: odfe-node1
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node1
      - discovery.seed_hosts=odfe-node1,odfe-node2
      - cluster.initial_master_nodes=odfe-node1,odfe-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - odfe-net
  odfe-node2:
    image: amazon/opendistro-for-elasticsearch:1.2.0
    container_name: odfe-node2
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node2
      - discovery.seed_hosts=odfe-node1,odfe-node2
      - cluster.initial_master_nodes=odfe-node1,odfe-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - odfe-data2:/usr/share/elasticsearch/data
    networks:
      - odfe-net
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.2.0
    container_name: odfe-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://odfe-node1:9200
      ELASTICSEARCH_HOSTS: https://odfe-node1:9200
    networks:
      - odfe-net

volumes:
  odfe-data1:
  odfe-data2:

networks:
  odfe-net:
```

**Comment by StewAlexanderACC** [comment]
Alright so after reformatting the yaml code to look like this:

```
--- 
networks: 
  odfe-net: ~
services: 
  kibana: 
    container_name: odfe-kibana
    environment: 
      ELASTICSEARCH_HOSTS: "https://odfe-node1:9200"
      ELASTICSEARCH_URL: "https://odfe-node1:9200"
    expose: 
      - "5601"
    image: "amazon/opendistro-for-elasticsearch-kibana:1.2.0"
    networks: 
      - odfe-net
    ports: 
      - "5601:5601"
  odfe-node1: 
    container_name: odfe-node1
    environment: 
      - cluster.name=odfe-cluster
      - node.name=odfe-node1
      - "discovery.seed_hosts=odfe-node1,odfe-node2"
      - "cluster.initial_master_nodes=odfe-node1,odfe-node2"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    image: "amazon/opendistro-for-elasticsearch:1.2.0"
    networks: 
      - odfe-net
    ports: 
      - "9200:9200"
      - "9600:9600"
    ulimits: 
      memlock: 
        hard: -1
        soft: -1
      nofile: 
        hard: 65536
        soft: 65536
    volumes: 
      - "odfe-data1:/usr/share/elasticsearch/data"
  odfe-node2: 
    container_name: odfe-node2
    environment: 
      - cluster.name=odfe-cluster
      - node.name=odfe-node2
      - "discovery.seed_hosts=odfe-node1,odfe-node2"
      - "cluster.initial_master_nodes=odfe-node1,odfe-node2"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    image: "amazon/opendistro-for-elasticsearch:1.2.0"
    networks: 
      - odfe-net
    ulimits: 
      memlock: 
        hard: -1
        soft: -1
      nofile: 
        hard: 65536
        soft: 65536
    volumes: 
      - "odfe-data2:/usr/share/elasticsearch/data"
version: "3"
volumes: 
  odfe-data1: ~
  odfe-data2: ~
```

I was able to get past the parser errors, however now I see the following when running docker-compose up:

```
odfe-kibana   | {"type":"log","@timestamp":"2019-11-20T17:02:49Z","tags":["status","plugin:ui_metric@7.2.0","info"],"pid":1,"state":"green","message":"Status changed                             from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
odfe-kibana   | {"type":"log","@timestamp":"2019-11-20T17:02:49Z","tags":["error","elasticsearch","admin"],"pid":1,"message":"Request error, retrying\nGET https://od                            fe-node1:9200/_nodes?filter_path=nodes.*.version%2Cnodes.*.http.publish_address%2Cnodes.*.ip => getaddrinfo ENOTFOUND odfe-node1 odfe-node1:9200"}
odfe-kibana   | {"type":"log","@timestamp":"2019-11-20T17:02:49Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: https://                            odfe-node1:9200/"}
odfe-kibana   | {"type":"log","@timestamp":"2019-11-20T17:02:49Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
odfe-kibana   | {"type":"log","@timestamp":"2019-11-20T17:02:49Z","tags":["status","plugin:elasticsearch@7.2.0","error"],"pid":1,"state":"red","message":"Status chan                            ged from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
odfe-kibana   | {"type":"log","@timestamp":"2019-11-20T17:02:52Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: https://                            odfe-node1:9200/"}
odfe-kibana   | {"type":"log","@timestamp":"2019-11-20T17:02:52Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
odfe-kibana   | {"type":"log","@timestamp":"2019-11-20T17:02:54Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: https://                            odfe-node1:9200/"}
odfe-kibana   | {"type":"log","@timestamp":"2019-11-20T17:02:54Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
odfe-kibana   | {"type":"log","@timestamp":"2019-11-20T17:02:57Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: https://   
```
