### ISSUE TITLE
filebeat 6.5.4 output to elasticsearch

### ISSUE THREAD

**Issue by HLLavender** [opendistro/for-elasticsearch-docs#21]
our filebeat is install of rpm,opendistro is install of docker。if i  want to edit filebet.yml send to  opendistro ,output.elasticsearch should be how to configure with authority

**Comment by aetter** [comment]
Hi @HLLavender, I'm not very familiar with FileBeat, but I believe it uses HTTP basic authentication. I don't see any reason why it wouldn't work with Open Distro for Elasticsearch and the Security plugin. Just for simplicity in testing, can you try the following?

```
output.elasticsearch:
  hosts: ["your-es-host:9200"]
  username: "admin"
  password: "admin" 
setup.kibana:
  host: "your-kibana-host:5601"
  username: "admin"  
  password: "admin"
```

And then if authentication doesn't work for some reason, try [disabling Security](https://opendistro.github.io/for-elasticsearch-docs/docs/security/disable/) and testing without credentials.

**Comment by HLLavender** [comment]
Hi@aetter ,i'm trying it ,but it's doesn't work

**Comment by HLLavender** [comment]
@aetter   i'm tried it ,but it doesn't work

**Comment by aetter** [comment]
Hi @HLLavender, I was able to get this working without too much fuss. Can you try the following?

```yml
output.elasticsearch:
  hosts: ["localhost:9200"]
  protocol: https
  username: "admin"
  password: "admin"
  ssl.certificate_authorities:
    - /full/path/to/root-ca.pem
  ssl.certificate: "/full/path/to/kirk.pem"
  ssl.key: "/full/path/to/kirk-key.pem"
```
