### ISSUE TITLE
Not able to map AD groups

### ISSUE THREAD

**Issue by jirisafar** [opendistro/for-elasticsearch-docs#40]
Hi,

please could you provide some guide how to connect OpenDistro with AD Groups? LDAP anesthetization works but how to define rules and access for that user?

Thanks a lot

**Comment by aetter** [comment]
Hi @jirisafar, can you clarify the request here? I'm not super familiar with AD, but my understanding is that we have content on pulling roles: https://opendistro.github.io/for-elasticsearch-docs/docs/security/ldap/#use-active-directory-and-ldap-for-authorization

**Comment by jirisafar** [comment]
Hi I have figure out that: I would like to add there a new section with document how to map AD groups. I have tried to pull this changes but with no luck.

There is a content:

---
layout: default
title: Permissions for AD/LDAP groups
nav_order: 98
has_children: true
has_toc: false
---

## How to manage permissions for specific AD group

To edit LDAP/AD authentication and authorization, for specific security group `/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml`:

```yml
all_access:
  readonly: false
  backendroles:
    - admin
    - your_AD_group_that_should_have_R/W_permissions
logstash:
  backendroles:
    - logstash
    
kibana_server:
  readonly: true
  users:
    - kibanaserver
    
kibana_user:
  backendroles:
    - kibanauser

readall:
  readonly: false
  backendroles:
    - readall
    - your_AD_group_that_should_have_R_permissions

manage_snapshots:
  readonly: true
  backendroles:
    - snapshotrestore

own_index:
  users:
    - '*'

LDAP/AD TEST:
  readonly: false
  backendroles:
    - test
    - your_ad_group
        ...
```
If you use CN in config.yml you always has to use CN for adding another group.

**Comment by coolgooze** [comment]
Working Setup with AD

ES Version: 6.6.2
OpenDistro: 0.8.0


Files to modify(/usr/share/elasticsearch/plugins/security/opendistro_security/)
config.yml
roles.yml
roles_mapping.yml

**Note**: Any change to above files, you need to re-run security_admin.sh script

Steps:
1. Enable SSL for elasticsearch using security_demo.sh script [ Strictly for development only ] 
2. Install OpenDistro for Kibana
3. If you have installed elasticsearch via RPM then add "
```xpack.security.enabled: false``` to elasticsearch.yml & kibana.yml
4. Modify roles.yml & roles_mapping.yml to include AD Group(Read Only Access)
```yaml
readall:
  readonly: true
  backendroles:
    - readall
    - '<Your AD Group>'
```
roles.yml
```yaml
# Read all, but no write permissions
readall:
  readonly: true
  cluster:
    - CLUSTER_ALL
  indices:
    '*':
      '*':
        - indices:admin/get
```
5. Update Security Index(Please replace paths and ESMASTER_IP)
```
```shell
/usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin.sh -cd "/usr/share/elasticsearch/plugins/opendistro_security/securityconfig" -icl -key "/etc/elasticsearch/kirk-key.pem" -cert "/etc/elasticsearch/kirk.pem" -cacert "/etc/elasticsearch/root-ca.pem" -nhnv -h <ES_MASTER_IP> -p 9300 -f /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml -t roles
/usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin.sh -cd "/usr/share/elasticsearch/plugins/opendistro_security/securityconfig" -icl -key "/etc/elasticsearch/kirk-key.pem" -cert "/etc/elasticsearch/kirk.pem" -cacert "/etc/elasticsearch/root-ca.pem" -nhnv -h <ES_MASTER_IP> -p 9300 -f /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml -t rolesmapping
/usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin.sh -cd "/usr/share/elasticsearch/plugins/opendistro_security/securityconfig" -icl -key "/etc/elasticsearch/kirk-key.pem" -cert "/etc/elasticsearch/kirk.pem" -cacert "/etc/elasticsearch/root-ca.pem" -nhnv -h <ES_MASTER_IP>-p 9300 -f /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml -t config
``````
6. Restart Elastic Search & Kibana

Bonus:
Config.yml for AD

```
```yaml
 ldap:
        enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: ldap
          config:
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: true
            hosts:
              - <AD_HOSTNAME>:389
            bind_dn: serviceaccount
            password: 'xxxxxx'
            userbase: 'OU=USERS,OU=CORPORATE,DC=com'
            usersearch: '(sAMAccountName={0})'
            username_attribute: sAMAccountName
    authz:
      roles_from_myldap:
        enabled: true
        authorization_backend:
          type: ldap
          config:
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: true
            hosts:
              - <AD_HOSTNAME>:389
            bind_dn: serviceaccount
            password: 'xxxxxx'
            rolebase: 'OU=GROUPS,DC=com'
            rolesearch: '(member={0})'
            userroleattribute: null
            userrolename: memberOf
            rolename: cn
            resolve_nested_roles: false
            userbase: 'OU=USERS,OU=CORPORATE,DC=com'
            usersearch: '(sAMAccountName={0})'
```
